### ISSUE TITLE
Error: Cannot find module 'lost'

### ISSUE THREAD

**Issue by lcpriest** [n1ru4l/ember-cli-postcss-fixed#1]
On a brand new EmberCLI project with no changes to it (version 1.13.8).

After following the Readme, `ember server` fails to run.

Error:

```
Cannot find module 'lost'
Error: Cannot find module 'lost'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/lcp/Development/Ember/postcss/node_modules/ember-cli-postcss-fixed/index.js:6:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by n1ru4l** [comment]
Fixed in https://github.com/n1ru4l/ember-cli-postcss-fixed/commit/316c62ebb455e335120741b44e28016d85728b0b
